### ISSUE TITLE
1 sentence become 2 lines in output.

### ISSUE THREAD

**Issue by ZeroCoder9324** [pgming-life/google-cloud-vision#1]
Output:
**To Pierre's inquiries as to what he must do and how he should
answer.**

The Output I want:
**To Pierre's inquiries as to what he must do and how he should answer.**

Image to Ocr:

![test](https://user-images.githubusercontent.com/72436418/140339480-899353e5-0e21-4e41-8d70-c2118845261f.png)

**Comment by pgming-life** [comment]
You seem to be misunderstanding.
OCR prints the image itself.
Does not interpret sentence connections.
